// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $api_docs_filename_ from "./routes/api/docs/[filename].ts";
import * as $api_login from "./routes/api/login.ts";
import * as $documents from "./routes/documents.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $logout from "./routes/logout.ts";
import * as $notes from "./routes/notes.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Theme from "./islands/Theme.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/_middleware.ts": $_middleware,
    "./routes/api/docs/[filename].ts": $api_docs_filename_,
    "./routes/api/login.ts": $api_login,
    "./routes/documents.tsx": $documents,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/logout.ts": $logout,
    "./routes/notes.tsx": $notes,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Theme.tsx": $Theme,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
